name: My-Automessage
version: '${project.version}'
main: pl.mymc.automessage.My_Automessage
author: WieszczY
website: https://github.com/WieszczY85/My-AutoMessage
api-version: 1.20.6
description: Plugin wyświetlający automatyczne wiadomości na czacie.
dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: false
commands:
  myautomessage:
    description: Wyświetla pomoc dla pluginu My_Automessage
    usage: |
      /<command> help - Wyświetla pomoc dla pluginu
      /<command> version - Wyświetla informacje o wersji pluginu
      /<command> reload - Przeładowuje plik konfiguracyjny
