name: My-Automessage
version: '${project.version}'
main: pl.mymc.automessage.My_Automessage
author: WieszczY
website: https://github.com/WieszczY85
api-version: 1.20.6
description: Plugin wyświetlający automatyczne wiadomości na czacie.
softdepend: [PlaceholderAPI]
commands:
  myautomessage:
    description: Wyświetla pomoc dla pluginu My_Automessage
    usage: |
      /<command> help - Wyświetla pomoc dla pluginu
      /<command> version - Wyświetla informacje o wersji pluginu

